spring.application.name=spring

#banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/spring
spring.datasource.username=postgres
spring.datasource.password=Alexbr1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:/db/changelog/liquibase.yaml

